### ISSUE TITLE
Add error messages when a task submission fails.

### ISSUE THREAD

**Issue by ZNLake** [SebOuellette/TaskSystem#15]
Frontend should display/output an appropriate error message in response to a conflict response (409) from the server as follows.

[
![NetworkFlow_add](https://github.com/SebOuellette/TaskSystem/assets/91035765/1818a3a5-eabb-4c06-8206-4da818af6ae9)
](url)

**Comment by SebOuellette** [comment]
This diagram was originally intended to display the client automatically sending a PUT request if it receives a 409 conflict. The status codes for the response from POST /add should be swapped. 
This feature has been implemented.
